<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Furniture;
use App\Models\FurnitureImage;
use App\Models\FurnitureModel;
use Illuminate\Database\Seeder;

class FurnitureSeeder extends Seeder
{
    /**
     * Seeds 40 curated, realistic furniture items across 9 subcategories
     * with representative physical dimensions based on typical furniture specifications.
     */
    public function run(): void
    {
        $categoryMap = Category::whereNotNull('parent_id')->pluck('id', 'slug');

        $items = [
            // -----------------------------------------------------------------
            // 1. Sofas & Lounging (6 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-001',
                'name' => 'Nordik 3-Seater Minimalist Sofa',
                'description' => 'Tailored three-seater sofa featuring clean architectural lines, high-density resilience foam, and tapered solid ash legs.',
                'price' => 849.00,
                'width_cm' => 210.00,
                'height_cm' => 82.00,
                'depth_cm' => 88.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 50.00,
                'style' => 'scandinavian',
                'material' => 'Linen Fabric & Ash Wood',
                'color' => 'Warm Grey',
                'color_hex' => '#A8A6A1',
            ],
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-002',
                'name' => 'Loft 2-Seater Compact Studio Sofa',
                'description' => 'Compact deep-seat loveseat ideal for urban apartments and smaller living spaces, upholstered in tactile boucle.',
                'price' => 580.00,
                'width_cm' => 152.00,
                'height_cm' => 78.00,
                'depth_cm' => 82.00,
                'clearance_front_cm' => 70.00,
                'clearance_side_cm' => 40.00,
                'style' => 'minimalist',
                'material' => 'Boucle Fabric',
                'color' => 'Cream White',
                'color_hex' => '#F3EFEA',
            ],
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-003',
                'name' => 'Manhattan L-Shaped Sectional Sofa',
                'description' => 'Generous family-sized corner sectional with right-hand chaise, wrapped in hand-finished top-grain saddle leather.',
                'price' => 1850.00,
                'width_cm' => 280.00,
                'height_cm' => 84.00,
                'depth_cm' => 165.00,
                'clearance_front_cm' => 90.00,
                'clearance_side_cm' => 60.00,
                'style' => 'modern',
                'material' => 'Top-Grain Leather',
                'color' => 'Cognac Brown',
                'color_hex' => '#8B4513',
            ],
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-004',
                'name' => 'Ironworks Industrial Tufted Loveseat',
                'description' => 'Rugged industrial loveseat pairing distressed caramel leather cushions with a welded blackened steel frame.',
                'price' => 920.00,
                'width_cm' => 165.00,
                'height_cm' => 80.00,
                'depth_cm' => 86.00,
                'clearance_front_cm' => 75.00,
                'clearance_side_cm' => 50.00,
                'style' => 'industrial',
                'material' => 'Aged Leather & Black Steel',
                'color' => 'Charcoal Brown',
                'color_hex' => '#3E3430',
            ],
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-005',
                'name' => 'Kyoto Low Platform Daybed',
                'description' => 'Zen-inspired minimalist daybed with an oiled American walnut frame and a supportive natural cotton futon cushion.',
                'price' => 740.00,
                'width_cm' => 195.00,
                'height_cm' => 65.00,
                'depth_cm' => 80.00,
                'clearance_front_cm' => 70.00,
                'clearance_side_cm' => 40.00,
                'style' => 'minimalist',
                'material' => 'Natural Walnut & Cotton',
                'color' => 'Sand Beige',
                'color_hex' => '#D2B48C',
            ],
            [
                'category_slug' => 'sofas-lounging',
                'sku' => 'SOFA-006',
                'name' => 'Chesterfield Heritage 3-Seater',
                'description' => 'Classic rolled-arm sofa featuring deep button-tufted upholstery in rich jewel-tone velvet.',
                'price' => 1450.00,
                'width_cm' => 225.00,
                'height_cm' => 76.00,
                'depth_cm' => 92.00,
                'clearance_front_cm' => 85.00,
                'clearance_side_cm' => 60.00,
                'style' => 'classic',
                'material' => 'Deep Buttoned Velvet',
                'color' => 'Forest Green',
                'color_hex' => '#1E3F20',
            ],

            // -----------------------------------------------------------------
            // 2. Coffee & Side Tables (4 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'coffee-side-tables',
                'sku' => 'COFF-001',
                'name' => 'Aura Oval Glass & Oak Coffee Table',
                'description' => 'Organic oval silhouette featuring a floating tempered glass surface resting on a sculptural solid white oak base.',
                'price' => 290.00,
                'width_cm' => 110.00,
                'height_cm' => 42.00,
                'depth_cm' => 60.00,
                'clearance_front_cm' => 50.00,
                'clearance_side_cm' => 50.00,
                'style' => 'scandinavian',
                'material' => 'Tempered Glass & Solid Oak',
                'color' => 'Natural Oak',
                'color_hex' => '#C8B195',
            ],
            [
                'category_slug' => 'coffee-side-tables',
                'sku' => 'COFF-002',
                'name' => 'Mono Block Minimalist Low Table',
                'description' => 'Architectural monolith table with a seamless micro-cement finish, grounding the living space in pure geometry.',
                'price' => 340.00,
                'width_cm' => 90.00,
                'height_cm' => 36.00,
                'depth_cm' => 90.00,
                'clearance_front_cm' => 45.00,
                'clearance_side_cm' => 45.00,
                'style' => 'minimalist',
                'material' => 'Micro-cement Finish',
                'color' => 'Matte Slate',
                'color_hex' => '#4A5056',
            ],
            [
                'category_slug' => 'coffee-side-tables',
                'sku' => 'COFF-003',
                'name' => 'Factory Round Nesting Tables (Pair)',
                'description' => 'Two nesting circular accent tables crafted from reclaimed teak planks with hand-welded iron band frames.',
                'price' => 260.00,
                'width_cm' => 80.00,
                'height_cm' => 45.00,
                'depth_cm' => 80.00,
                'clearance_front_cm' => 40.00,
                'clearance_side_cm' => 40.00,
                'style' => 'industrial',
                'material' => 'Reclaimed Teak & Matte Black Iron',
                'color' => 'Distressed Teak',
                'color_hex' => '#634735',
            ],
            [
                'category_slug' => 'coffee-side-tables',
                'sku' => 'COFF-004',
                'name' => 'Verona Marble Rectangular Coffee Table',
                'description' => 'Honed Italian Carrara marble slab mounted on an understated satin brass architectural underframe.',
                'price' => 620.00,
                'width_cm' => 120.00,
                'height_cm' => 40.00,
                'depth_cm' => 65.00,
                'clearance_front_cm' => 50.00,
                'clearance_side_cm' => 50.00,
                'style' => 'modern',
                'material' => 'Carrara Marble & Brass',
                'color' => 'Carrara White',
                'color_hex' => '#F0EEE9',
            ],

            // -----------------------------------------------------------------
            // 3. Media & TV Units (4 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'media-tv-units',
                'sku' => 'TV-001',
                'name' => 'Horizon 180 Floating Wall Console',
                'description' => 'Wall-mounted floating media unit with integrated cable raceway, push-to-open acoustic fabric drop-down fronts.',
                'price' => 420.00,
                'width_cm' => 180.00,
                'height_cm' => 32.00,
                'depth_cm' => 38.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 30.00,
                'style' => 'minimalist',
                'material' => 'Matte Lacquer & Oak Veneer',
                'color' => 'Arctic White / Oak',
                'color_hex' => '#F8F8F8',
            ],
            [
                'category_slug' => 'media-tv-units',
                'sku' => 'TV-002',
                'name' => 'Oslo Low Media Bench 200cm',
                'description' => 'Substantial Nordic entertainment credenza featuring tambour slatted sliding doors and wire-pass dividers.',
                'price' => 680.00,
                'width_cm' => 200.00,
                'height_cm' => 48.00,
                'depth_cm' => 45.00,
                'clearance_front_cm' => 90.00,
                'clearance_side_cm' => 40.00,
                'style' => 'scandinavian',
                'material' => 'Solid White Oak & Slatted Doors',
                'color' => 'Nordic Oak',
                'color_hex' => '#DEC5A5',
            ],
            [
                'category_slug' => 'media-tv-units',
                'sku' => 'TV-003',
                'name' => 'Brooklyn Steel-Mesh Credenza',
                'description' => 'Heavy-gauge steel frame with perforated mesh doors allowing remote control IR pass-through, topped with aged elm.',
                'price' => 540.00,
                'width_cm' => 160.00,
                'height_cm' => 60.00,
                'depth_cm' => 42.00,
                'clearance_front_cm' => 75.00,
                'clearance_side_cm' => 30.00,
                'style' => 'industrial',
                'material' => 'Perforated Steel & Elm Wood',
                'color' => 'Industrial Black',
                'color_hex' => '#262626',
            ],
            [
                'category_slug' => 'media-tv-units',
                'sku' => 'TV-004',
                'name' => 'Palais Walnut Sideboard Console',
                'description' => 'Substantial mid-century influenced sideboard with bookmatched walnut veneer and brushed antique brass pulls.',
                'price' => 890.00,
                'width_cm' => 175.00,
                'height_cm' => 75.00,
                'depth_cm' => 46.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 35.00,
                'style' => 'classic',
                'material' => 'American Walnut & Brass Knobs',
                'color' => 'Dark Walnut',
                'color_hex' => '#442B15',
            ],

            // -----------------------------------------------------------------
            // 4. Beds & Mattresses (5 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'beds-mattresses',
                'sku' => 'BED-001',
                'name' => 'Fjord Single Platform Bed (90x200)',
                'description' => 'Clean-lined solid birch bed frame designed for standard single 90x200 cm mattresses with integrated posture slats.',
                'price' => 380.00,
                'width_cm' => 98.00,
                'height_cm' => 90.00,
                'depth_cm' => 208.00,
                'clearance_front_cm' => 60.00,
                'clearance_side_cm' => 60.00,
                'style' => 'scandinavian',
                'material' => 'Solid Birch',
                'color' => 'Light Birch',
                'color_hex' => '#E6DAC8',
            ],
            [
                'category_slug' => 'beds-mattresses',
                'sku' => 'BED-002',
                'name' => 'Astrid Queen Upholstered Bed (160x200)',
                'description' => 'Curved shelter headboard upholstered in durable heathered woven fabric with padded perimeter rails.',
                'price' => 790.00,
                'width_cm' => 172.00,
                'height_cm' => 110.00,
                'depth_cm' => 215.00,
                'clearance_front_cm' => 75.00,
                'clearance_side_cm' => 60.00,
                'style' => 'modern',
                'material' => 'Textured Woven Fabric & Foam',
                'color' => 'Muted Sand',
                'color_hex' => '#D7CEC7',
            ],
            [
                'category_slug' => 'beds-mattresses',
                'sku' => 'BED-003',
                'name' => 'Skan King Hydraulic Storage Bed (180x200)',
                'description' => 'Effortless gas-lift hydraulic mechanism revealing cavernous under-bed storage without sacrificing clean Nordic aesthetics.',
                'price' => 1150.00,
                'width_cm' => 194.00,
                'height_cm' => 105.00,
                'depth_cm' => 216.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 65.00,
                'style' => 'scandinavian',
                'material' => 'Oak Veneer with Gas-Lift Storage',
                'color' => 'Natural Oak',
                'color_hex' => '#C2A382',
            ],
            [
                'category_slug' => 'beds-mattresses',
                'sku' => 'BED-004',
                'name' => 'Zen Low Tatami Platform King (180x200)',
                'description' => 'Ultra-low Japanese minimalist platform bed with an extended perimeter ledge crafted from sustainably harvested cedar.',
                'price' => 690.00,
                'width_cm' => 210.00,
                'height_cm' => 30.00,
                'depth_cm' => 220.00,
                'clearance_front_cm' => 60.00,
                'clearance_side_cm' => 50.00,
                'style' => 'minimalist',
                'material' => 'Solid Cedar & Ash',
                'color' => 'Raw Wood',
                'color_hex' => '#CEB89E',
            ],
            [
                'category_slug' => 'beds-mattresses',
                'sku' => 'BED-005',
                'name' => 'Grand Master Tufted King Bed (180x200)',
                'description' => 'High diamond-tufted linen headboard with handcrafted fluted posts for an elegant master bedroom aesthetic.',
                'price' => 1320.00,
                'width_cm' => 196.00,
                'height_cm' => 140.00,
                'depth_cm' => 222.00,
                'clearance_front_cm' => 85.00,
                'clearance_side_cm' => 70.00,
                'style' => 'classic',
                'material' => 'Padded Linen & Carved Wood',
                'color' => 'Oatmeal',
                'color_hex' => '#E3DAC9',
            ],

            // -----------------------------------------------------------------
            // 5. Nightstands & Bedside Storage (4 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'nightstands',
                'sku' => 'NST-001',
                'name' => 'Aero Floating Bedside Shelf',
                'description' => 'Wall-hung curved nightstand with concealed soft-close drawer, keeping floor space completely open.',
                'price' => 95.00,
                'width_cm' => 42.00,
                'height_cm' => 18.00,
                'depth_cm' => 32.00,
                'clearance_front_cm' => 50.00,
                'clearance_side_cm' => 20.00,
                'style' => 'minimalist',
                'material' => 'Bent Ash Plywood',
                'color' => 'Natural Ash',
                'color_hex' => '#DFD2C0',
            ],
            [
                'category_slug' => 'nightstands',
                'sku' => 'NST-002',
                'name' => 'Linnea 2-Drawer Oak Nightstand',
                'description' => 'Classic Scandinavian bedside chest with dovetailed joinery and recessed brass finger pulls.',
                'price' => 165.00,
                'width_cm' => 48.00,
                'height_cm' => 54.00,
                'depth_cm' => 40.00,
                'clearance_front_cm' => 55.00,
                'clearance_side_cm' => 25.00,
                'style' => 'scandinavian',
                'material' => 'Solid Oak & Brass Pulls',
                'color' => 'Honey Oak',
                'color_hex' => '#C99E6B',
            ],
            [
                'category_slug' => 'nightstands',
                'sku' => 'NST-003',
                'name' => 'Foundry Open Wire Bedside Cube',
                'description' => 'Minimalist open-cage bedside locker featuring blackened iron mesh and a removable solid mango wood top.',
                'price' => 120.00,
                'width_cm' => 40.00,
                'height_cm' => 50.00,
                'depth_cm' => 38.00,
                'clearance_front_cm' => 45.00,
                'clearance_side_cm' => 20.00,
                'style' => 'industrial',
                'material' => 'Powder-coated Steel & Mango Wood',
                'color' => 'Matte Black',
                'color_hex' => '#222222',
            ],
            [
                'category_slug' => 'nightstands',
                'sku' => 'NST-004',
                'name' => 'Grace Fluted Cylinder Pedestal',
                'description' => 'Round architectural nightstand with textured fluted casing and an inset engineered white stone top.',
                'price' => 210.00,
                'width_cm' => 38.00,
                'height_cm' => 52.00,
                'depth_cm' => 38.00,
                'clearance_front_cm' => 45.00,
                'clearance_side_cm' => 20.00,
                'style' => 'modern',
                'material' => 'Fluted Ceramic & Marble Top',
                'color' => 'Ivory White',
                'color_hex' => '#F5F5F0',
            ],

            // -----------------------------------------------------------------
            // 6. Desks & Workstations (4 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'desks-workstations',
                'sku' => 'DSK-001',
                'name' => 'Solo Compact Study Desk 100x50',
                'description' => 'Slender workspace desk specifically proportioned for bedrooms and studio apartments with an integrated monitor shelf.',
                'price' => 185.00,
                'width_cm' => 100.00,
                'height_cm' => 75.00,
                'depth_cm' => 50.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 30.00,
                'style' => 'minimalist',
                'material' => 'Laminate & White Steel Frame',
                'color' => 'White / Birch',
                'color_hex' => '#EBEAE6',
            ],
            [
                'category_slug' => 'desks-workstations',
                'sku' => 'DSK-002',
                'name' => 'ErgoPro Motorized Sit-Stand Desk 140x70',
                'description' => 'Dual-motor electric height-adjustable desk with memory presets, solid walnut desktop, and anti-collision sensor.',
                'price' => 580.00,
                'width_cm' => 140.00,
                'height_cm' => 72.00,
                'depth_cm' => 70.00,
                'clearance_front_cm' => 90.00,
                'clearance_side_cm' => 40.00,
                'style' => 'modern',
                'material' => 'Solid Walnut Top & Dual Motor Base',
                'color' => 'Warm Walnut',
                'color_hex' => '#5C4033',
            ],
            [
                'category_slug' => 'desks-workstations',
                'sku' => 'DSK-003',
                'name' => 'Architect Drafting Studio Desk',
                'description' => 'Industrial drafting table with adjustable incline top, cast-iron crank wheels, and rustic pine timbers.',
                'price' => 440.00,
                'width_cm' => 150.00,
                'height_cm' => 76.00,
                'depth_cm' => 75.00,
                'clearance_front_cm' => 85.00,
                'clearance_side_cm' => 40.00,
                'style' => 'industrial',
                'material' => 'Cast Iron Trestles & Rustic Pine',
                'color' => 'Raw Pine / Cast Iron',
                'color_hex' => '#876543',
            ],
            [
                'category_slug' => 'desks-workstations',
                'sku' => 'DSK-004',
                'name' => 'Executive L-Shaped Corner Workstation',
                'description' => 'Comprehensive executive desk providing generous desktop area and integrated lockable filing drawers.',
                'price' => 790.00,
                'width_cm' => 180.00,
                'height_cm' => 75.00,
                'depth_cm' => 140.00,
                'clearance_front_cm' => 95.00,
                'clearance_side_cm' => 50.00,
                'style' => 'modern',
                'material' => 'Smoked Oak & Charcoal Metal',
                'color' => 'Smoked Oak',
                'color_hex' => '#3B332C',
            ],

            // -----------------------------------------------------------------
            // 7. Dining Tables (3 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'dining-tables',
                'sku' => 'DTB-001',
                'name' => 'Circa 4-Seater Round Dining Table',
                'description' => 'Warm round solid ash table with conical pedestal base, maximizing knee clearance and intimacy in compact dining nooks.',
                'price' => 520.00,
                'width_cm' => 110.00,
                'height_cm' => 75.00,
                'depth_cm' => 110.00,
                'clearance_front_cm' => 80.00,
                'clearance_side_cm' => 80.00,
                'style' => 'scandinavian',
                'material' => 'Solid Ash with Pedestal Base',
                'color' => 'Blonde Ash',
                'color_hex' => '#E2D3B8',
            ],
            [
                'category_slug' => 'dining-tables',
                'sku' => 'DTB-002',
                'name' => 'Kanso 6-Seater Rectangular Dining Table',
                'description' => 'Pure minimalist dining table crafted from wide planks of solid European white oak with soft radius edges.',
                'price' => 740.00,
                'width_cm' => 160.00,
                'height_cm' => 76.00,
                'depth_cm' => 90.00,
                'clearance_front_cm' => 85.00,
                'clearance_side_cm' => 60.00,
                'style' => 'minimalist',
                'material' => 'Solid White Oak',
                'color' => 'Natural Oak',
                'color_hex' => '#CCB290',
            ],
            [
                'category_slug' => 'dining-tables',
                'sku' => 'DTB-003',
                'name' => 'Bastion 8-Seater Extendable Dining Table',
                'description' => 'Substantial live-edge walnut dining table with a butterfly internal extension mechanism expanding up to 260 cm.',
                'price' => 1180.00,
                'width_cm' => 200.00,
                'height_cm' => 76.00,
                'depth_cm' => 95.00,
                'clearance_front_cm' => 90.00,
                'clearance_side_cm' => 70.00,
                'style' => 'industrial',
                'material' => 'Live-Edge Walnut & U-Steel Legs',
                'color' => 'Deep Walnut',
                'color_hex' => '#4A3525',
            ],

            // -----------------------------------------------------------------
            // 8. Dining Chairs (6 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-001',
                'name' => 'Fawn Scandinavian Spindle Dining Chair',
                'description' => 'Timeless Windsor-inspired dining chair with turned beech spindles and a saddled ergonomic wooden seat.',
                'price' => 95.00,
                'width_cm' => 46.00,
                'height_cm' => 82.00,
                'depth_cm' => 49.00,
                'clearance_front_cm' => 50.00,
                'clearance_side_cm' => 20.00,
                'style' => 'scandinavian',
                'material' => 'Bentwood Beech',
                'color' => 'Natural Beech',
                'color_hex' => '#D8C6A5',
            ],
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-002',
                'name' => 'Port Upholstered Curved Back Armchair',
                'description' => 'Plush wrap-around curved back dining chair providing generous lumbar support during long dinner parties.',
                'price' => 155.00,
                'width_cm' => 56.00,
                'height_cm' => 78.00,
                'depth_cm' => 54.00,
                'clearance_front_cm' => 55.00,
                'clearance_side_cm' => 25.00,
                'style' => 'modern',
                'material' => 'Tweed Fabric & Matte Black Legs',
                'color' => 'Charcoal Grey',
                'color_hex' => '#404040',
            ],
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-003',
                'name' => 'Cantilever Chrome Leatherette Chair',
                'description' => 'Bauhaus-influenced S-curve tubular steel cantilever chair providing comfortable natural flex.',
                'price' => 130.00,
                'width_cm' => 48.00,
                'height_cm' => 84.00,
                'depth_cm' => 52.00,
                'clearance_front_cm' => 50.00,
                'clearance_side_cm' => 20.00,
                'style' => 'modern',
                'material' => 'Tubular Steel & Saddle Faux Leather',
                'color' => 'Caramel Brown',
                'color_hex' => '#A0522D',
            ],
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-004',
                'name' => 'Bento Minimalist Molded Shell Chair',
                'description' => 'Ultra-lightweight stackable molded polypropylene chair with matte texture and solid beech dowel legs.',
                'price' => 75.00,
                'width_cm' => 48.00,
                'height_cm' => 79.00,
                'depth_cm' => 47.00,
                'clearance_front_cm' => 45.00,
                'clearance_side_cm' => 20.00,
                'style' => 'minimalist',
                'material' => 'Recycled Polypropylene & Wood',
                'color' => 'Chalk White',
                'color_hex' => '#F0EDE6',
            ],
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-005',
                'name' => 'Bistro Wire Metal Dining Chair',
                'description' => 'Geometric wire grid chair with an electroplated gunmetal finish and a magnetic vegan leather seat cushion.',
                'price' => 88.00,
                'width_cm' => 44.00,
                'height_cm' => 80.00,
                'depth_cm' => 46.00,
                'clearance_front_cm' => 45.00,
                'clearance_side_cm' => 20.00,
                'style' => 'industrial',
                'material' => 'Welded Steel Rod with Leather Pad',
                'color' => 'Gunmetal Grey',
                'color_hex' => '#33373B',
            ],
            [
                'category_slug' => 'dining-chairs',
                'sku' => 'DCH-006',
                'name' => 'Heritage Oak Dining Bench 140cm',
                'description' => 'Sturdy solid oak bench that slides completely under 160+ cm dining tables when not in active use.',
                'price' => 210.00,
                'width_cm' => 140.00,
                'height_cm' => 46.00,
                'depth_cm' => 36.00,
                'clearance_front_cm' => 40.00,
                'clearance_side_cm' => 20.00,
                'style' => 'scandinavian',
                'material' => 'Solid Oak with Rounded Edges',
                'color' => 'Natural Oak',
                'color_hex' => '#CDB18B',
            ],

            // -----------------------------------------------------------------
            // 9. Accent & Storage Units (4 items)
            // -----------------------------------------------------------------
            [
                'category_slug' => 'accent-storage',
                'sku' => 'STG-001',
                'name' => 'Gridline Tall Open Modular Bookcase',
                'description' => 'Architectural steel frame bookcase featuring 5 staggered shelves of natural ash, perfect for room zoning.',
                'price' => 340.00,
                'width_cm' => 90.00,
                'height_cm' => 190.00,
                'depth_cm' => 34.00,
                'clearance_front_cm' => 70.00,
                'clearance_side_cm' => 25.00,
                'style' => 'minimalist',
                'material' => 'Powder-coated Steel & Ash Shelves',
                'color' => 'Matte Black & Ash',
                'color_hex' => '#2A2927',
            ],
            [
                'category_slug' => 'accent-storage',
                'sku' => 'STG-002',
                'name' => 'Lattice Timber Room Divider / Screen',
                'description' => 'Freestanding vertical timber slat screen with an integrated planter box for creating privacy and zones in open plans.',
                'price' => 390.00,
                'width_cm' => 120.00,
                'height_cm' => 175.00,
                'depth_cm' => 30.00,
                'clearance_front_cm' => 60.00,
                'clearance_side_cm' => 30.00,
                'style' => 'scandinavian',
                'material' => 'Vertical Oak Slats & Planter Box',
                'color' => 'Nordic Oak',
                'color_hex' => '#D5BE9E',
            ],
            [
                'category_slug' => 'accent-storage',
                'sku' => 'STG-003',
                'name' => 'Hygge Cocoon Reading Armchair',
                'description' => 'Comfortable reading accent chair upholstered in plush shearling fleece with a 360-degree silent swivel oak base.',
                'price' => 540.00,
                'width_cm' => 84.00,
                'height_cm' => 92.00,
                'depth_cm' => 82.00,
                'clearance_front_cm' => 75.00,
                'clearance_side_cm' => 40.00,
                'style' => 'scandinavian',
                'material' => 'Shearling Fleece & Oak Swivel Base',
                'color' => 'Warm Oatmeal',
                'color_hex' => '#EAE6DF',
            ],
            [
                'category_slug' => 'accent-storage',
                'sku' => 'STG-004',
                'name' => 'Foyer Entryway Bench & Coat Rack',
                'description' => 'Multifunctional entry hall unit with a lower slatted shoe bench, cushioned seat, and 6 cast-iron coat hooks.',
                'price' => 260.00,
                'width_cm' => 100.00,
                'height_cm' => 180.00,
                'depth_cm' => 40.00,
                'clearance_front_cm' => 70.00,
                'clearance_side_cm' => 20.00,
                'style' => 'industrial',
                'material' => 'Reclaimed Pine & Black Iron Pipes',
                'color' => 'Dark Oak / Iron',
                'color_hex' => '#3A2E28',
            ],
        ];

        foreach ($items as $itemData) {
            $categorySlug = $itemData['category_slug'];
            unset($itemData['category_slug']);

            $categoryId = $categoryMap[$categorySlug] ?? null;
            if (!$categoryId) {
                continue;
            }

            $sku = $itemData['sku'];
            $itemData['category_id'] = $categoryId;
            
            // Only assign glb_model_path if physical file exists on disk
            $glbRelative = "furniture/models/{$sku}.glb";
            $hasGlb = file_exists(storage_path("app/public/{$glbRelative}"));
            $itemData['glb_model_path'] = $hasGlb ? "/storage/furniture/models/{$sku}.glb" : null;

            $furniture = Furniture::firstOrCreate(['sku' => $sku], $itemData);

            // Seed primary preview image record
            FurnitureImage::firstOrCreate(
                [
                    'furniture_id' => $furniture->id,
                    'is_primary' => true,
                ],
                [
                    'image_path' => "/storage/furniture/images/{$sku}-primary.webp",
                    'sort_order' => 1,
                ]
            );

            // Seed 3D GLB model record only if physical model exists
            if ($hasGlb) {
                FurnitureModel::firstOrCreate(
                    [
                        'furniture_id' => $furniture->id,
                        'format' => 'glb',
                    ],
                    [
                        'model_path' => "/storage/furniture/models/{$sku}.glb",
                        'file_size_mb' => round(filesize(storage_path("app/public/{$glbRelative}")) / (1024 * 1024), 2),
                        'is_optimized' => true,
                        'draco_compressed' => true,
                    ]
                );
            }
        }
    }
}
