import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# \ud83d\udecb\ufe0f SmartSpace: AI 3D Furniture Generator\n",
                "### Google Colab Free GPU Pipeline (Option B)\n",
                "**Powered by TripoSR (Stability AI & VAST AI Research)**\n",
                "\n",
                "This notebook converts 2D furniture photographs into textured 3D `.glb` models in ~5-10 seconds using a free Google Colab T4 GPU.\n",
                "\n",
                "> **Capstone Defense Note**: In SmartSpace, AI generates the initial perceptual 3D geometry mesh, while SmartSpace's deterministic geometry engine mathematically normalizes the bounding box to exact verified catalog dimensions (`width_cm`, `depth_cm`, `height_cm`) upon loading into Three.js.\n",
                "\n",
                "---\n",
                "### \ud83d\ude80 Step 0: Ensure GPU is Enabled\n",
                "Go to **Runtime > Change runtime type > T4 GPU** before running the cells."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \u2699\ufe0f 1. Install Dependencies & Clone TripoSR\n",
                "import torch\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"GPU: {torch.cuda.get_device_name(0)}\")\n",
                "else:\n",
                "    print(\"\u26a0\ufe0f WARNING: GPU not detected! Please go to Runtime > Change runtime type > T4 GPU\")\n",
                "\n",
                "!git clone https://github.com/VAST-AI-Research/TripoSR.git\n",
                "%cd TripoSR\n",
                "!pip install -q -U \"numpy>=2.0.0\" \"scipy>=1.14.0\" trimesh einops omegaconf \"rembg[gpu,cli]\" pygltflib PyMCubes\n",
                "!pip install -q --no-build-isolation git+https://github.com/tatsy/torchmcubes.git || echo 'Using PyMCubes fallback'\n",
                "print(\"\\n[OK] Environment ready!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \ud83e\udde0 2. Load TripoSR Pretrained Model\n",
                "import os\n",
                "import sys\n",
                "import types\n",
                "import time\n",
                "import numpy as np\n",
                "import torch\n",
                "from PIL import Image\n",
                "import trimesh\n",
                "\n",
                "# Marching cubes compatibility bridge (prevents any missing C-extension crashes)\n",
                "try:\n",
                "    import torchmcubes\n",
                "except ImportError:\n",
                "    try:\n",
                "        import mcubes\n",
                "        mod = types.ModuleType(\"torchmcubes\")\n",
                "        def mc_fallback(volume, threshold=0.0):\n",
                "            v_np = volume.detach().cpu().numpy()\n",
                "            verts, faces = mcubes.marching_cubes(v_np, float(threshold))\n",
                "            return torch.from_numpy(verts.copy()).to(volume.device).float(), torch.from_numpy(faces.copy().astype(np.int64)).to(volume.device)\n",
                "        mod.marching_cubes = mc_fallback\n",
                "        sys.modules[\"torchmcubes\"] = mod\n",
                "        print(\"[*] Using PyMCubes marching cubes engine\")\n",
                "    except Exception:\n",
                "        from skimage.measure import marching_cubes as ski_mc\n",
                "        mod = types.ModuleType(\"torchmcubes\")\n",
                "        def mc_fallback_ski(volume, threshold=0.0):\n",
                "            v_np = volume.detach().cpu().numpy()\n",
                "            verts, faces, _, _ = ski_mc(v_np, level=float(threshold))\n",
                "            return torch.from_numpy(verts.copy()).to(volume.device).float(), torch.from_numpy(faces.copy().astype(np.int64)).to(volume.device)\n",
                "        mod.marching_cubes = mc_fallback_ski\n",
                "        sys.modules[\"torchmcubes\"] = mod\n",
                "        print(\"[*] Using scikit-image marching cubes engine\")\n",
                "\n",
                "from tsr.system import TSR\n",
                "from tsr.utils import remove_background, resize_foreground\n",
                "\n",
                "# Automatic weight key remapper for newer transformers versions\n",
                "_orig_load_sd = TSR.load_state_dict\n",
                "def _patched_load_sd(self, state_dict, strict=True, assign=False):\n",
                "    model_keys = list(self.state_dict().keys())\n",
                "    if any('layers.0.attention.q_proj' in k for k in model_keys) and any('encoder.layer.0.attention.attention.query' in k for k in state_dict.keys()):\n",
                "        print('[*] Adapting checkpoint weights to newer transformers layer naming...')\n",
                "        new_sd = {}\n",
                "        for k, v in state_dict.items():\n",
                "            nk = k.replace('encoder.layer.', 'layers.')\n",
                "            nk = nk.replace('.attention.attention.query.', '.attention.q_proj.')\n",
                "            nk = nk.replace('.attention.attention.key.', '.attention.k_proj.')\n",
                "            nk = nk.replace('.attention.attention.value.', '.attention.v_proj.')\n",
                "            nk = nk.replace('.attention.output.dense.', '.attention.o_proj.')\n",
                "            nk = nk.replace('.intermediate.dense.', '.mlp.fc1.')\n",
                "            nk = nk.replace('.output.dense.', '.mlp.fc2.')\n",
                "            new_sd[nk] = v\n",
                "        state_dict = new_sd\n",
                "    try:\n",
                "        return _orig_load_sd(self, state_dict, strict=strict, assign=assign)\n",
                "    except TypeError:\n",
                "        return _orig_load_sd(self, state_dict, strict=strict)\n",
                "TSR.load_state_dict = _patched_load_sd\n",
                "\n",
                "device = \"cuda:0\" if torch.cuda.is_available() else \"cpu\"\n",
                "print(f\"Loading TripoSR weights onto {device}...\")\n",
                "model = TSR.from_pretrained(\n",
                "    \"stabilityai/TripoSR\",\n",
                "    config_name=\"config.yaml\",\n",
                "    weight_name=\"model.ckpt\",\n",
                ")\n",
                "model.renderer.set_chunk_size(8192)\n",
                "model.to(device)\n",
                "print(\"[\u2713] TripoSR loaded successfully!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \ud83d\udcf8 3. Select Furniture SKU or Upload Image\n",
                "from google.colab import files\n",
                "import urllib.request\n",
                "\n",
                "# @markdown Choose an existing SmartSpace catalog SKU or choose CUSTOM_UPLOAD:\n",
                "sku_preset = \"COFF-001 (Coffee Table)\" # @param [\"COFF-001 (Coffee Table)\", \"DCH-001 (Dining Chair)\", \"SOFA-002 (Modern Loveseat)\", \"TV-001 (TV Media Console)\", \"CUSTOM_UPLOAD\"]\n",
                "custom_sku = \"COFF-001\" # @param {type:\"string\"}\n",
                "\n",
                "input_image_path = \"input_furniture.png\"\n",
                "current_sku = custom_sku.strip()\n",
                "\n",
                "# Sample catalog reference images\n",
                "preset_samples = {\n",
                "    \"COFF-001\": \"https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600&auto=format&fit=crop&q=80\",\n",
                "    \"DCH-001\": \"https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80\",\n",
                "    \"SOFA-002\": \"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80\",\n",
                "    \"TV-001\": \"https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600&auto=format&fit=crop&q=80\"\n",
                "}\n",
                "\n",
                "if \"CUSTOM\" in sku_preset:\n",
                "    print(\"Please upload a photo of your furniture:\")\n",
                "    uploaded = files.upload()\n",
                "    uploaded_file = list(uploaded.keys())[0]\n",
                "    Image.open(uploaded_file).convert(\"RGB\").save(input_image_path)\n",
                "    print(f\"[\u2713] Custom image uploaded for SKU: {current_sku}\")\n",
                "else:\n",
                "    sku_code = sku_preset.split(\" \")[0]\n",
                "    current_sku = sku_code\n",
                "    url = preset_samples.get(sku_code)\n",
                "    print(f\"Fetching catalog reference image for {sku_code}...\")\n",
                "    urllib.request.urlretrieve(url, input_image_path)\n",
                "    print(f\"[\u2713] Loaded image for SKU: {current_sku}\")\n",
                "\n",
                "raw_img = Image.open(input_image_path)\n",
                "display(raw_img.resize((300, 300)))"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \u26a1 4. Generate 3D Geometry & Export to .GLB\n",
                "resolution = 256 # @param [128, 256, 384, 512]\n",
                "\n",
                "t_start = time.time()\n",
                "print(\"[*] Preprocessing image (rembg background removal)...\")\n",
                "proc_img = remove_background(raw_img.convert(\"RGB\"))\n",
                "proc_img = resize_foreground(proc_img, ratio=0.85)\n",
                "\n",
                "print(\"[*] Generating 3D neural radiance fields with TripoSR...\")\n",
                "with torch.no_grad():\n",
                "    scene_codes = model(proc_img, device=device)\n",
                "\n",
                "print(f\"[*] Extracting isosurface mesh (marching cubes {resolution}^3)...\")\n",
                "meshes = model.extract_mesh(scene_codes, resolution=resolution)\n",
                "mesh = meshes[0]\n",
                "\n",
                "verts = mesh.vertices.detach().cpu().numpy()\n",
                "faces = mesh.faces.detach().cpu().numpy()\n",
                "v_colors = mesh.vertex_colors.detach().cpu().numpy()\n",
                "if v_colors.max() <= 1.0:\n",
                "    v_colors = (v_colors * 255).astype(np.uint8)\n",
                "\n",
                "t_mesh = trimesh.Trimesh(vertices=verts, faces=faces, vertex_colors=v_colors, process=True)\n",
                "t_mesh.apply_translation(-t_mesh.centroid)\n",
                "\n",
                "output_glb_name = f\"{current_sku}.glb\"\n",
                "t_mesh.export(output_glb_name, file_type=\"glb\")\n",
                "\n",
                "elapsed = time.time() - t_start\n",
                "file_size_mb = os.path.getsize(output_glb_name) / (1024 * 1024)\n",
                "print(f\"\\n[\u2713] SUCCESS: Generated {output_glb_name} ({file_size_mb:.2f} MB) in {elapsed:.1f}s!\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \ud83d\udd0d 5. Interactive 3D Preview (In-Browser)\n",
                "from IPython.display import HTML\n",
                "import base64\n",
                "\n",
                "with open(output_glb_name, \"rb\") as f:\n",
                "    glb_b64 = base64.b64encode(f.read()).decode(\"ascii\")\n",
                "\n",
                "html_code = f\"\"\"\n",
                "<script type=\\\"module\\\" src=\\\"https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js\\\"></script>\n",
                "<div style=\\\"width: 100%; display: flex; flex-direction: column; align-items: center; background: #1a1a24; border-radius: 12px; padding: 20px;\\\">\n",
                "  <h3 style=\\\"color: #f1f5f9; font-family: sans-serif; margin-bottom: 12px;\\\">Interactive 3D Preview: {output_glb_name}</h3>\n",
                "  <model-viewer \n",
                "    src=\\\"data:model/gltf-binary;base64,{glb_b64}\\\"\n",
                "    camera-controls \n",
                "    auto-rotate \n",
                "    shadow-intensity=\\\"1\\\"\n",
                "    style=\\\"width: 100%; height: 420px; background-color: #0f172a; border-radius: 8px;\\\">\n",
                "  </model-viewer>\n",
                "  <p style=\\\"color: #94a3b8; font-family: sans-serif; font-size: 13px; margin-top: 10px;\\\">\n",
                "    \ud83d\uddb1\ufe0f Left click + drag to rotate | Right click to pan | Scroll to zoom\n",
                "  </p>\n",
                "</div>\n",
                "\"\"\"\n",
                "display(HTML(html_code))"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {"cellView": "form"},
            "outputs": [],
            "source": [
                "# @title \ud83d\udcbe 6. Download GLB to Local SmartSpace Project\n",
                "from google.colab import files\n",
                "print(f\"Downloading {output_glb_name}...\")\n",
                "files.download(output_glb_name)\n",
                "\n",
                "print(\"\"\"\n",
                "========================================================================\n",
                "\ud83c\udf89 NEXT STEPS IN SMARTSPACE:\n",
                "1. Move the downloaded file to:\n",
                "   backend/storage/app/public/furniture/models/\n",
                "2. Double-click sync-models.bat (or run php artisan furniture:sync-models)\n",
                "3. Refresh your SmartSpace browser tab \u2014 the 3D model is active!\n",
                "========================================================================\n",
                "\"\"\")"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

os.makedirs("colab", exist_ok=True)
with open("colab/SmartSpace_AI_3D_Generator.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

# Also place a copy in project root for instant visibility
with open("SmartSpace_AI_3D_Generator.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)

print("[OK] Generated colab/SmartSpace_AI_3D_Generator.ipynb and SmartSpace_AI_3D_Generator.ipynb successfully!")
